version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
